FROM python:3.8-slim-buster

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Copy the files.
COPY ./foreign_oidc_rp/requirements.txt ./requirements.txt

# Install dependencies.
RUN pip install -r requirements.txt

# Set development mode.
ENV FLASK_ENV=development