FROM python:3.8-slim-buster

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Copy the files.
COPY ./home_oidc_idp/requirements.txt ./requirements.txt

# Install dependencies.
RUN pip install -r requirements.txt