stages:
  - build
  - deploy

build-package:
  stage: build
  image: faucet/dbuilder
  script:
    - apt-get update && apt-get upgrade -y
    - mk-build-deps -i -r -t 'apt-get -f -y --force-yes'
    - export DEBEMAIL='maintainers@faucet.nz' && export DEBFULLNAME='Faucet Maintainers'
    - debchange --newversion ${CI_COMMIT_REF_NAME} -b "New upstream release"
    - dpkg-buildpackage -b -us -uc -rfakeroot
    - mkdir built-packages || true
    - mv ../*.deb built-packages/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

deploy-package:
  stage: deploy
  image: faucet/dbuilder
  script:
    - cd built-packages/
    - ../gitlab/deploy_deb.sh
  only:
    - tags
