dist: bionic
sudo: required
cache:
  pip: true
stages:
  - test
  - name: deploy
    if: repo = faucetsdn/chewie AND tag IS present
services:
  - docker
script:
  - ./travis/runtests.sh
jobs:
  include:
    - stage: test
      language: python
      python: 3.5
      env:
        - TRAVIS_SHARD=unittest
    - stage: test
      language: python
      python: 3.6
      env:
        - TRAVIS_SHARD=unittest
        - CODE_CHECK=true
        - CODE_COV=true
    - stage: test
      language: python
      python: 3.7
      env: TRAVIS_SHARD=unittest
    - stage: test
      env: TRAVIS_SHARD=integration
      before_install:
        - docker pull faucet/test-base
      language: bash
      services:
        - docker
    - stage: deploy
      language: python
      python: 3.6
      install: skip
      before_script: skip
      script: skip
      after_script: skip
      deploy:
        provider: pypi
        on:
          tags: true
        user: __token__
        password:
          secure: W5VKAd2M2YlEFKfSxbRDHr8oPRS0wU0nHnUu2UZA0CLJIZZ2D4PBu2ZLc42L3xb4TPz6VBistP3wT9kJuJo9a3b7dvwe8TmttxrGDbWILpdmsSLE4bUqTdVRW+mouIfZqRxEzMWgEY27piCYBMpwAVI9+NIfFof+reqfpLT4Dken+rbhmR7vgW+zmKFQXkRTrV+a4KA6UuqRwnVtA8+/NGWzEyypeqPi9p6tVRekqt4MKs0LZk5M9z5aaInEFur2Ff2H8V6LMCvSVzU4sCqTTUPPs34uBscGL7e9x/22/cYSrElTx9DBDeIGiMtOk0Wlwxg++ynV5lPsuFrbnBuo6VrU4l+A1JSh6jYNF5rNOjtoQHwnI0P0TTvBGvOZGfkjYHSgtm2HJ3T1jrChUvYMchMUNQA3uvPvJ3Tbwg14rkflyoCxCGSmGF7WzMUwxF/YuntdLGYy83MnyybJ3teP5P01+wuFplR2lPyhsHJQo/Ckxaaa76O5eCPJ0i/klOzDXpKqvBTCfAp9KS9gXcKF0p+hd8gb6w8Gjk5GY6HnXQOvbf95DntqDWqmufgH+hgiYvNv4e1cPSv9gqrFllWdk5UihOn4WJ6wcmQ2luNYlhH92Xband84b7M642GmdFyy5ozoc1ynMkeVcNM/cEUA06A8oGWH7AA/f/7Q2tBb/WU=
